### ISSUE TITLE
Timing until found pattern or address

### ISSUE THREAD

**Issue by bigvito19** [Limeth/ethaddrgen#1]
Could you add an time probability until found pattern or address

**Comment by Limeth** [comment]
Do you mean some kind of way to measure how long it took to generate the address?
If so, you can use the `time` command if you're on unix, otherwise there probably is a similar command on Windows, too:
```
$ time ethaddrgen abcd
---------------------------------------------------------------------------------------
Looking for an address matching 1 pattern
---------------------------------------------------------------------------------------
71743 addresses / second
---------------------------------------------------------------------------------------
Found address: removed
Generated private key: removed
Import this private key into an ethereum wallet in order to use the address.
Buy me a cup of coffee; my ethereum address: 0xc0ffee3bd37d408910ecab316a07269fc49a20ee
---------------------------------------------------------------------------------------
5.08user 0.05system 0:01.33elapsed 385%CPU (0avgtext+0avgdata 6732maxresident)k
0inputs+0outputs (0major+1618minor)pagefaults 0swaps
```

**Comment by Limeth** [comment]
I read your message incorrectly;
as far as computing how long it would take to generate an address matching a certain pattern, it would be trivial for regular non-regex patterns, but when it comes to regex patterns, I imagine it would be too difficult to implement, or I currently have no idea how I would do it.
I will keep it in mind, though.

**Comment by bigvito19** [comment]
Can you give me an example of a non-regex pattern and a regex pattern

**Comment by Limeth** [comment]
Regex: `ethaddrgen -e "^\\d{8}"` (generates addresses starting with 8 digits)
Non-regex: `ethaddrgen "abcdef"` (generates addresses starting with "abcdef")

**Comment by Limeth** [comment]
I'll close this as it doesn't seem to fall into the project's scope.
