### ISSUE TITLE
Reading patterns from a file

### ISSUE THREAD

**Issue by band1k1** [Limeth/ethaddrgen#3]
It's very helpful! 
Can you explain how to load patterns from a file .txt ?  
How can I add more than 200 patterns?
I have a file patterns like:
1a1a1a
2a2a2a
1b1b1b
2b2b2b 
etc.

**Comment by Limeth** [comment]
Hello, I'm glad you find it useful.
In order to load patterns from a file, you need to send those patterns into stdin;
on Windows, this should work:
```powershell
Get-Content patterns.txt | ethaddrgen
```
on Unix systems, one of the following does the job:
```sh
cat patterns.txt | ethaddrgen
# or
ethaddrgen < patterns.txt
```

**Comment by Limeth** [comment]
Also, I've this PR of something I wanted to finish. I've just released a new version of ethaddrgen with better performance for pattern lists, give it a try. ;)

**Comment by band1k1** [comment]
Thank you! 
How can i update ethaddrgen?

**Comment by Limeth** [comment]
Just download the latest build from https://github.com/Limeth/ethaddrgen/releases.
