### ISSUE TITLE
please help me output

### ISSUE THREAD

**Issue by successhalf** [Limeth/ethaddrgen#6]
please help me output in results.txt
" ethaddrgen.exe -e 00 -q results.txt"
Not save to results.txt I tried

**Comment by Limeth** [comment]
I personally don't have experience with redirecting outputs to a file on windows, but [this stackoverflow question](https://stackoverflow.com/questions/1215260/how-to-redirect-the-output-of-a-powershell-to-a-file-during-its-execution) seems to address the issue.

**Comment by successhalf** [comment]
> I personally don't have experience with redirecting outputs to a file on windows, but [this stackoverflow question](https://stackoverflow.com/questions/1215260/how-to-redirect-the-output-of-a-powershell-to-a-file-during-its-execution) seems to address the issue.

So how do you save the address and private key ?

**Comment by Limeth** [comment]
On Unix systems, it is as simple as doing `ethaddrgen -e 00 -q > results.txt`, but you would have to follow that stackoverflow question to figure out how to do it on Windows, which I am not familiar with.

**Comment by Limeth** [comment]
Closing the issue due to inactivity.
